{
 "title": "windows_exporter for Prometheus Dashboard EN v20221025",
 "description": "windows_exporter 0.20.0  && Grafana 9      Original author @starsl.cn. (id: 10467).    modified by: Alliot (www.iots.vip)",
 "tags": [
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(windows_cs_hostname, job)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\"}, hostname)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",hostname=~\"$hostname\"}, instance)"
    }
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",instance=~\"$instance\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource overview（Associate job item）Currently selected host：【$show_hostname】Instance：$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$job：Overview of server resources",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\"} * on(instance) group_right(product) windows_cs_hostname"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\"} - 0"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\"}"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"C:\"})"
    },
    {
     "expr": "max by (instance) (1-windows_logical_disk_free_bytes{job=~\"$job\"}/windows_logical_disk_size_bytes{job=~\"$job\"})"
    },
    {
     "expr": "windows_os_processes{job=~\"$job\"}"
    },
    {
     "expr": "sum by (instance) (windows_service_state{job=~\"$job\",state=~\"running\"})"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "memory usage"
    },
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU usage of each host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage of each host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network details of the maximum traffic network interface of each host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_net_bytes_sent_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_net_bytes_received_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Maximum disk read and write details for each host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_read_bytes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_读取",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_write_bytes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_写入",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Details of the maximum disk IO of each host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_reads_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_读取",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_writes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_写入",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Resource Details【$show_hostname：$instance】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[2m])))*100"
    }
   ]
  },
  {
   "title": "usage of each partition",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "service status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{job=~\"$job\",instance=~\"$instance\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "number of processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_processes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "进程数"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "memory total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "memory detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "total memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "available memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_virtual_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Virtual memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "windows_os_virtual_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Free virtual memory"
    }
   ]
  },
  {
   "title": "Disk free space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "available {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "total {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "network detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_sent_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8>0\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Sent-upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_received_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Received-download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "disk read and write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_reads_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_writes_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "network usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(irate(windows_net_bytes_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m]) * 8 / windows_net_current_bandwidth_bytes{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_outbound_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "outbound",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_outbound_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "received",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "system_threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "system_threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System exception dispatches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_system_exception_dispatches_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "exceptions",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}